export const TYPE_COLORS: Record<string, string> = {
  normal: "#A8A878",
  fire: "#F08030",
  water: "#6890F0",
  electric: "#F8D030",
  grass: "#78C850",
  ice: "#98D8D8",
  fighting: "#C03028",
  poison: "#A040A0",
  ground: "#E0C068",
  flying: "#A890F0",
  psychic: "#F85888",
  bug: "#A8B820",
  rock: "#B8A038",
  ghost: "#705898",
  dragon: "#7038F8",
  dark: "#705848",
  steel: "#B8B8D0",
  fairy: "#EE99AC",
};

export const LISTA_PAISES: { code: string; name: string; iso: string }[] = [
  { code: "ND", name: "No definido", iso: "" },
  { code: "ES", name: "España", iso: "es" },
  { code: "MX", name: "México", iso: "mx" },
  { code: "AR", name: "Argentina", iso: "ar" },
  { code: "CO", name: "Colombia", iso: "co" },
  { code: "CL", name: "Chile", iso: "cl" },
  { code: "PE", name: "Perú", iso: "pe" },
  { code: "EC", name: "Ecuador", iso: "ec" },
  { code: "VE", name: "Venezuela", iso: "ve" },
  { code: "GT", name: "Guatemala", iso: "gt" },
  { code: "CR", name: "Costa Rica", iso: "cr" },
  { code: "UY", name: "Uruguay", iso: "uy" },
  { code: "PY", name: "Paraguay", iso: "py" },
  { code: "BO", name: "Bolivia", iso: "bo" },
  { code: "DO", name: "Rep. Dominicana", iso: "do" },
  { code: "US", name: "Estados Unidos", iso: "us" },
];
