export const TYPE_COLORS: Record<string, string> = {
  fuego: "#ef4444",
  fire: "#ef4444",
  agua: "#3b82f6",
  water: "#3b82f6",
  planta: "#22c55e",
  grass: "#22c55e",
  electrico: "#eab308",
  electric: "#eab308",
  hielo: "#06b6d4",
  ice: "#06b6d4",
  lucha: "#dc2626",
  fighting: "#dc2626",
  veneno: "#a855f7",
  poison: "#a855f7",
  tierra: "#ca8a04",
  ground: "#ca8a04",
  volador: "#8b5cf6",
  flying: "#8b5cf6",
  psiquico: "#ec4899",
  psychic: "#ec4899",
  bicho: "#84cc16",
  bug: "#84cc16",
  roca: "#b45309",
  rock: "#b45309",
  fantasma: "#6366f1",
  ghost: "#6366f1",
  dragon: "#7c3aed",
  siniestro: "#475569",
  dark: "#475569",
  acero: "#64748b",
  steel: "#64748b",
  hada: "#f472b6",
  fairy: "#f472b6",
  normal: "#94a3b8",
};

export const TYPE_TRANSLATIONS: Record<string, string> = {
  fire: "Fuego",
  water: "Agua",
  grass: "Planta",
  electric: "Eléctrico",
  ice: "Hielo",
  fighting: "Lucha",
  poison: "Veneno",
  ground: "Tierra",
  flying: "Volador",
  psychic: "Psíquico",
  bug: "Bicho",
  rock: "Roca",
  ghost: "Fantasma",
  dragon: "Dragón",
  dark: "Siniestro",
  steel: "Acero",
  fairy: "Hada",
  normal: "Normal",
  fuego: "Fuego",
  agua: "Agua",
  planta: "Planta",
  electrico: "Eléctrico",
  hielo: "Hielo",
  lucha: "Lucha",
  veneno: "Veneno",
  tierra: "Tierra",
  volador: "Volador",
  psiquico: "Psíquico",
  bicho: "Bicho",
  roca: "Roca",
  fantasma: "Fantasma",
  siniestro: "Siniestro",
  acero: "Acero",
  hada: "Hada",
};

export const LISTA_PAISES: { code: string; name: string; iso: string }[] = [
  { code: "ND", name: "No definido", iso: "" },
  { code: "ES", name: "España", iso: "es" },
  { code: "MX", name: "México", iso: "mx" },
  { code: "AR", name: "Argentina", iso: "ar" },
  { code: "CO", name: "Colombia", iso: "co" },
  { code: "CL", name: "Chile", iso: "cl" },
  { code: "PE", name: "Perú", iso: "pe" },
  { code: "EC", name: "Ecuador", iso: "ec" },
  { code: "VE", name: "Venezuela", iso: "ve" },
  { code: "GT", name: "Guatemala", iso: "gt" },
  { code: "CR", name: "Costa Rica", iso: "cr" },
  { code: "UY", name: "Uruguay", iso: "uy" },
  { code: "PY", name: "Paraguay", iso: "py" },
  { code: "BO", name: "Bolivia", iso: "bo" },
  { code: "DO", name: "Rep. Dominicana", iso: "do" },
  { code: "US", name: "Estados Unidos", iso: "us" },
];
