import type { Metadata } from "next";
import Navbar2 from "../components/Navbarv2";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className="bg-gray-900 text-white">
        <Navbar2 />
        <main className="pt-24 min-h-screen">
          {" "}
          {children}
        </main>
      </body>
    </html>
  );
}
