import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../components/Navbar";
import Navbar2 from "../components/Navbarv2";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className="bg-gray-900 text-white">
        <Navbar2 /> {/* <-- Aquí vive el Navbar globalmente */}
        <main className="pt-24 min-h-screen">
          {" "}
          {/* El padding superior evita que el contenido se tape */}
          {children}
        </main>
      </body>
    </html>
  );
}
